global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kvraft
    metrics_path: /metrics
    static_configs:
      - targets:
          - kvraft-1:8000
          - kvraft-2:8000
          - kvraft-3:8000
        labels:
          cluster: kvraft-local
